
trigger: 
- master

pool: 
  vmImage: 'ubuntu-latest'
  demands: 
  - maven
  - python3

variables: 
- name: var1
  value: 'hello'

- name: var2
  value: 'world'

steps:
- bash: echo "$(var1)$(var2)"
- powershell: mvn --version
- bash: python3 --version